# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convolution function for homogeneous semi-Markov models
#' 
#' @param time_vector,integrand_1,integrand_2 Numeric vectors.
#' @export
convolute_semiMarkov <- function(time_vector, integrand_1, integrand_2) {
    .Call(`_ebsurv_convolute_semiMarkov`, time_vector, integrand_1, integrand_2)
}

#' Convolution function for homogeneous Markov models
#' 
#' @param time_vector,integrand_1,integrand_2 Numeric vectors.
#' @export
convolute_Markov <- function(time_vector, diff_vector, probtrans_vector_1, probtrans_vector_2) {
    .Call(`_ebsurv_convolute_Markov`, time_vector, diff_vector, probtrans_vector_1, probtrans_vector_2)
}

