# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convolute two vectors
#' 
#' @param time_vector,integrand_1,integrand_2 Numeric vectors.
#' @export
convolute_semiMarkov <- function(time_vector, integrand_1, integrand_2) {
    .Call(`_ebsurv_convolute_semiMarkov`, time_vector, integrand_1, integrand_2)
}

